# Generated by Django 3.0 on 2019-12-07 20:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pepper.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('original_price', models.FloatField(blank=True, default=None)),
                ('retail_price', models.FloatField()),
                ('still_up_to_date', models.BooleanField(default=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pepper.Category')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
