# Generated by Django 3.0.1 on 2019-12-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepper_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slugged_category',
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
