# Generated by Django 3.0 on 2019-12-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepper_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='original_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
