# Generated by Django 3.0.1 on 2019-12-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepper_app', '0002_auto_20191226_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
        migrations.AddField(
            model_name='category',
            name='slugged_category',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
