# Generated by Django 3.0 on 2019-12-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepper_app', '0002_auto_20191207_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='retail_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
