# Generated by Django 3.0.1 on 2019-12-26 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pepper_app', '0003_auto_20191226_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='slugged_subcategory',
        ),
    ]
