# Generated by Django 3.0.1 on 2019-12-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepper_app', '0004_remove_subcategory_slugged_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='slugged_subcategory',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
