# Generated by Django 3.0 on 2019-12-10 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pepper_app', '0007_auto_20191210_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='slug',
            new_name='slugged_title',
        ),
    ]
