# Generated by Django 3.0 on 2019-12-10 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pepper_app', '0008_auto_20191210_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slugged_title',
        ),
    ]
