# Generated by Django 3.0.1 on 2019-12-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepper_app', '0010_item_slugged_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slugged_title',
            field=models.SlugField(blank=True),
        ),
    ]
